In [5]:
from google.cloud import bigquery
import pandas as pd

In [9]:
client = bigquery.Client(location=" europe-west2")
print("Client creating using default project: {}".format(client.project))
query = """
SELECT SPECIES, ISLAND, culmen_length_mm, culmen_depth_mm, flipper_length_mm, body_mass_g, sex
FROM `ons-ids-analysis-uat.uat_wip_notebook.penguins`
"""
query_job = client.query(
query,
# Location must match that of the dataset(s) referenced in the query.
location="europe-west2",
) # API request - starts the query

all_metrics = query_job.to_dataframe()
all_metrics

Client creating using default project: ons-ids-analysis-uat

,SPECIES,ISLAND,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Gentoo penguin (Pygoscelis papua),Biscoe,NaN,NaN,NaN,NaN,None
1,Gentoo penguin (Pygoscelis papua),Biscoe,47.3,13.8,216.0,4725.0,None
2,Gentoo penguin (Pygoscelis papua),Biscoe,44.5,14.3,216.0,4100.0,None
3,Gentoo penguin (Pygoscelis papua),Biscoe,46.2,14.4,214.0,4650.0,None
4,Gentoo penguin (Pygoscelis papua),Biscoe,44.5,15.7,217.0,4875.0,.
...,...,...,...,...,...,...,...
339,Chinstrap penguin (Pygoscelis antarctica),Dream,50.2,18.7,198.0,3775.0,FEMALE
340,Chinstrap penguin (Pygoscelis antarctica),Dream,45.2,16.6,191.0,3250.0,FEMALE
341,Chinstrap penguin (Pygoscelis antarctica),Dream,46.4,17.8,191.0,3700.0,FEMALE
342,Chinstrap penguin (Pygoscelis antarctica),Dream,47.5,16.8,199.0,3900.0,FEMALE
343,Chinstrap penguin (Pygoscelis antarctica),Dream,48.1,16.4,199.0,3325.0,FEMALE